// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/platforms/jfrog/proto/admiral_secret.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAccountSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountSecretsRequest) Reset() {
	*x = ListAccountSecretsRequest{}
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountSecretsRequest) ProtoMessage() {}

func (x *ListAccountSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountSecretsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescGZIP(), []int{0}
}

type ListAccountSecretsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountSecrets *AccountSecrets        `protobuf:"bytes,1,opt,name=account_secrets,json=accountSecrets,proto3" json:"account_secrets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAccountSecretsResponse) Reset() {
	*x = ListAccountSecretsResponse{}
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountSecretsResponse) ProtoMessage() {}

func (x *ListAccountSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountSecretsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescGZIP(), []int{1}
}

func (x *ListAccountSecretsResponse) GetAccountSecrets() *AccountSecrets {
	if x != nil {
		return x.AccountSecrets
	}
	return nil
}

type AccountSecrets struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Secrets       []*EnvironmentSecretMetadata `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSecrets) Reset() {
	*x = AccountSecrets{}
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSecrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSecrets) ProtoMessage() {}

func (x *AccountSecrets) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSecrets.ProtoReflect.Descriptor instead.
func (*AccountSecrets) Descriptor() ([]byte, []int) {
	return file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescGZIP(), []int{2}
}

func (x *AccountSecrets) GetSecrets() []*EnvironmentSecretMetadata {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type EnvironmentSecretMetadata struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Identifier    *EnvironmentSecretIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CreatedAt     *timestamppb.Timestamp       `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUpdatedAt *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentSecretMetadata) Reset() {
	*x = EnvironmentSecretMetadata{}
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentSecretMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentSecretMetadata) ProtoMessage() {}

func (x *EnvironmentSecretMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentSecretMetadata.ProtoReflect.Descriptor instead.
func (*EnvironmentSecretMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescGZIP(), []int{3}
}

func (x *EnvironmentSecretMetadata) GetIdentifier() *EnvironmentSecretIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *EnvironmentSecretMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnvironmentSecretMetadata) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

type EnvironmentSecretIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentSecretIdentifier) Reset() {
	*x = EnvironmentSecretIdentifier{}
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentSecretIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentSecretIdentifier) ProtoMessage() {}

func (x *EnvironmentSecretIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentSecretIdentifier.ProtoReflect.Descriptor instead.
func (*EnvironmentSecretIdentifier) Descriptor() ([]byte, []int) {
	return file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescGZIP(), []int{4}
}

func (x *EnvironmentSecretIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvironmentSecretIdentifier) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

var File_pkg_platforms_jfrog_proto_admiral_secret_proto protoreflect.FileDescriptor

const file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDesc = "" +
	"\n" +
	".pkg/platforms/jfrog/proto/admiral_secret.proto\x12\x16qwak.admiral.secret.v0\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\x19ListAccountSecretsRequest\"m\n" +
	"\x1aListAccountSecretsResponse\x12O\n" +
	"\x0faccount_secrets\x18\x01 \x01(\v2&.qwak.admiral.secret.v0.AccountSecretsR\x0eaccountSecrets\"]\n" +
	"\x0eAccountSecrets\x12K\n" +
	"\asecrets\x18\x01 \x03(\v21.qwak.admiral.secret.v0.EnvironmentSecretMetadataR\asecrets\"\xef\x01\n" +
	"\x19EnvironmentSecretMetadata\x12S\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v23.qwak.admiral.secret.v0.EnvironmentSecretIdentifierR\n" +
	"identifier\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x0flast_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\"X\n" +
	"\x1bEnvironmentSecretIdentifier\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId2\x8c\x01\n" +
	"\rSecretService\x12{\n" +
	"\x12ListAccountSecrets\x121.qwak.admiral.secret.v0.ListAccountSecretsRequest\x1a2.qwak.admiral.secret.v0.ListAccountSecretsResponseBBZ@github.com/praetorian-inc/trajan/pkg/platforms/jfrog/proto;protob\x06proto3"

var (
	file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescOnce sync.Once
	file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescData []byte
)

func file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescGZIP() []byte {
	file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescOnce.Do(func() {
		file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDesc), len(file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDesc)))
	})
	return file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDescData
}

var file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_platforms_jfrog_proto_admiral_secret_proto_goTypes = []any{
	(*ListAccountSecretsRequest)(nil),   // 0: qwak.admiral.secret.v0.ListAccountSecretsRequest
	(*ListAccountSecretsResponse)(nil),  // 1: qwak.admiral.secret.v0.ListAccountSecretsResponse
	(*AccountSecrets)(nil),              // 2: qwak.admiral.secret.v0.AccountSecrets
	(*EnvironmentSecretMetadata)(nil),   // 3: qwak.admiral.secret.v0.EnvironmentSecretMetadata
	(*EnvironmentSecretIdentifier)(nil), // 4: qwak.admiral.secret.v0.EnvironmentSecretIdentifier
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_pkg_platforms_jfrog_proto_admiral_secret_proto_depIdxs = []int32{
	2, // 0: qwak.admiral.secret.v0.ListAccountSecretsResponse.account_secrets:type_name -> qwak.admiral.secret.v0.AccountSecrets
	3, // 1: qwak.admiral.secret.v0.AccountSecrets.secrets:type_name -> qwak.admiral.secret.v0.EnvironmentSecretMetadata
	4, // 2: qwak.admiral.secret.v0.EnvironmentSecretMetadata.identifier:type_name -> qwak.admiral.secret.v0.EnvironmentSecretIdentifier
	5, // 3: qwak.admiral.secret.v0.EnvironmentSecretMetadata.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: qwak.admiral.secret.v0.EnvironmentSecretMetadata.last_updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: qwak.admiral.secret.v0.SecretService.ListAccountSecrets:input_type -> qwak.admiral.secret.v0.ListAccountSecretsRequest
	1, // 6: qwak.admiral.secret.v0.SecretService.ListAccountSecrets:output_type -> qwak.admiral.secret.v0.ListAccountSecretsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_platforms_jfrog_proto_admiral_secret_proto_init() }
func file_pkg_platforms_jfrog_proto_admiral_secret_proto_init() {
	if File_pkg_platforms_jfrog_proto_admiral_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDesc), len(file_pkg_platforms_jfrog_proto_admiral_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_platforms_jfrog_proto_admiral_secret_proto_goTypes,
		DependencyIndexes: file_pkg_platforms_jfrog_proto_admiral_secret_proto_depIdxs,
		MessageInfos:      file_pkg_platforms_jfrog_proto_admiral_secret_proto_msgTypes,
	}.Build()
	File_pkg_platforms_jfrog_proto_admiral_secret_proto = out.File
	file_pkg_platforms_jfrog_proto_admiral_secret_proto_goTypes = nil
	file_pkg_platforms_jfrog_proto_admiral_secret_proto_depIdxs = nil
}
