// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: pkg/platforms/jfrog/proto/edge_secret.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeSecretService_GetSecret_FullMethodName = "/qwak.secret.service.EdgeSecretService/GetSecret"
)

// EdgeSecretServiceClient is the client API for EdgeSecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EdgeSecretService provides secret value operations
type EdgeSecretServiceClient interface {
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
}

type edgeSecretServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeSecretServiceClient(cc grpc.ClientConnInterface) EdgeSecretServiceClient {
	return &edgeSecretServiceClient{cc}
}

func (c *edgeSecretServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, EdgeSecretService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeSecretServiceServer is the server API for EdgeSecretService service.
// All implementations must embed UnimplementedEdgeSecretServiceServer
// for forward compatibility.
//
// EdgeSecretService provides secret value operations
type EdgeSecretServiceServer interface {
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	mustEmbedUnimplementedEdgeSecretServiceServer()
}

// UnimplementedEdgeSecretServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeSecretServiceServer struct{}

func (UnimplementedEdgeSecretServiceServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedEdgeSecretServiceServer) mustEmbedUnimplementedEdgeSecretServiceServer() {}
func (UnimplementedEdgeSecretServiceServer) testEmbeddedByValue()                           {}

// UnsafeEdgeSecretServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeSecretServiceServer will
// result in compilation errors.
type UnsafeEdgeSecretServiceServer interface {
	mustEmbedUnimplementedEdgeSecretServiceServer()
}

func RegisterEdgeSecretServiceServer(s grpc.ServiceRegistrar, srv EdgeSecretServiceServer) {
	// If the following call panics, it indicates UnimplementedEdgeSecretServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeSecretService_ServiceDesc, srv)
}

func _EdgeSecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeSecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeSecretService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeSecretServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeSecretService_ServiceDesc is the grpc.ServiceDesc for EdgeSecretService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeSecretService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qwak.secret.service.EdgeSecretService",
	HandlerType: (*EdgeSecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _EdgeSecretService_GetSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/platforms/jfrog/proto/edge_secret.proto",
}
